#!/bin/sh

#
# Copyright © 2015 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

##############################################################################
#
#   gradlew start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradlew
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/3d91ce3b8caaf77ad09f381f43615b715b53f72c/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s\n' "$PWD" ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac



# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='-Dfile.encoding=UTF-8 "-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
#     treated as '${Hostname}' itself on the command line.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

# ---------------------------------------------------------------------
# NullArmy: surface build failures as GitHub check annotations.
#
# CI logs for this repository are stored on a host that is not reachable from
# every environment, so a failed build could otherwise be invisible: "exit code
# 1" and nothing else. Everything Gradle prints is still streamed to stdout
# exactly as before (tee), the real exit status is preserved, and on failure the
# interesting lines are re-emitted as ::error:: workflow commands, which GitHub
# turns into annotations that can be read through the API.
#
# Nothing here changes what is built or how. Remove the block and restore the
# single line  exec "$JAVACMD" "$@"  to get the stock wrapper back.
# ---------------------------------------------------------------------
NULLARMY_LOG="${TMPDIR:-/tmp}/nullarmy-build.$$.log"
NULLARMY_STATUS="${TMPDIR:-/tmp}/nullarmy-build.$$.status"

{
    "$JAVACMD" "$@"
    echo $? > "$NULLARMY_STATUS"
} 2>&1 | tee "$NULLARMY_LOG"

if [ -f "$NULLARMY_STATUS" ]; then
    NULLARMY_EXIT=$(cat "$NULLARMY_STATUS")
else
    NULLARMY_EXIT=1
fi

# Always report the runtime smoke test's own verdict. "The build passed" says
# nothing about whether a Null was actually visible on a live server, so the
# verdict and the check lines are re-emitted as a notice annotation, readable
# through the API and shown in the Checks UI. Failures and the verdict come
# first: GitHub truncates a long annotation message.
if [ -f "$NULLARMY_LOG" ]; then
    awk '
        /RUNTIME SMOKE: / {
            line = $0; sub(/\r$/, "", line); gsub(/%/, "%%", line)
            head = head line "%0A"; next
        }
        /\[NullArmy\]\[SELFTEST\] .*FAIL/ {
            line = $0; sub(/\r$/, "", line); gsub(/%/, "%%", line)
            head = head line "%0A"; next
        }
        /\[NullArmy\]\[SELFTEST\] (RESULT|starting|adapter|arrival|pairing path|shutdown progress|dismissed)/ {
            line = $0; sub(/\r$/, "", line); gsub(/%/, "%%", line)
            head = head line "%0A"; next
        }
        /\[NullArmy\]\[SELFTEST\] PASS/ {
            line = $0; sub(/\r$/, "", line); gsub(/%/, "%%", line)
            passes = passes line "%0A"; npass++; next
        }
        END {
            body = head passes
            if (length(body) > 3800) {
                body = substr(body, 1, 3800) " %0A(truncated - the full list is in the server log artifact)"
            }
            if (npass + length(head) == 0) {
                printf("::notice title=NullArmy runtime smoke test::no smoke test output - it did not run\n")
            } else {
                printf("::notice title=NullArmy runtime smoke test (%d PASS lines)::%s\n", npass, body)
            }
        }
    ' "$NULLARMY_LOG"
fi

if [ "$NULLARMY_EXIT" -ne 0 ] && [ -f "$NULLARMY_LOG" ]; then
    awk '
        match($0, /\.java:[0-9]+: error:/) {
            line = $0
            sub(/\r$/, "", line)
            n = index(line, ":")
            file = substr(line, 1, n - 1)
            rest = substr(line, n + 1)
            m = index(rest, ":")
            lineno = substr(rest, 1, m - 1)
            msg = substr(rest, m + 2)
            gsub(/%/, "%%", msg)
            printf("::error file=%s,line=%s::%s\n", file, lineno, msg)
            raw = $0
            gsub(/%/, "%%", raw)
            printf("::error::%s\n", raw)
            next
        }
        /FAILURE: |What went wrong|^Caused by:|Execution failed for task|error:|BUILD FAILED|RUNTIME SMOKE: FAIL|RUNTIME SMOKE: BLOCKED|\[NullArmy\]\[SELFTEST\]|  FAIL  |^FAILURES:|^  - |^passed: / {
            line = $0
            sub(/\r$/, "", line)
            gsub(/%/, "%%", line)
            printf("::error::%s\n", line)
        }
    ' "$NULLARMY_LOG" | head -n 80
    echo "::error::NullArmy build failed with exit code $NULLARMY_EXIT - see the annotations above"
fi

rm -f "$NULLARMY_LOG" "$NULLARMY_STATUS"
exit "$NULLARMY_EXIT"
